#!/bin/bash

if [[ $(pidof pipewire | wc -c) -eq 0 ]]; then
    exec pipewire &
fi

if [[ $(pidof pipewire-pulse | wc -c) -eq 0 ]]; then
    exec pipewire-pulse &
fi

if [[ $(pidof wireplumber | wc -c) -eq 0 ]]; then
    exec wireplumber &
fi

if [[ $(pidof picom | wc -c) -eq 0 ]]; then
    exec picom &
fi

if [[ $(pidof thunar | wc -c) -eq 0 ]]; then
    exec thunar --daemon &
fi

if [[ $(pidof xss-lock | wc -c) -eq 0 ]]; then
    exec xss-lock env XSECURELOCK_COMPOSITE_OBSCURER=0 xsecurelock &
fi

if [[ $(pidof kdeconnect-indicator | wc -c) -eq 0 ]]; then
    exec kdeconnect-indicator &
fi

if [[ $(pidof xfce-polkit | wc -c) -eq 0 ]]; then
    exec /usr/libexec/xfce-polkit &
fi

if [[ $(pidof xfce4-power-manager | wc -c) -eq 0 ]]; then
    exec xfce4-power-manager &
fi

if [[ $(pidof playerctld | wc -c) -eq 0 ]]; then
    exec playerctld daemon &
fi

if [[ $(pidof mpris-proxy | wc -c) -eq 0 ]]; then
    exec mpris-proxy &
fi

if ! mountpoint -q /mnt/nextcloud ; then
    exec mount /mnt/nextcloud &
fi

if [[ $(pidof gamemoded | wc -c) -eq 0 ]]; then
    exec gamemoded &
fi

if [[ $(pgrep blueman-applet | wc -c) -eq 0 ]]; then
    exec blueman-applet &
fi

if [[ $(pidof keepassxc | wc -c) -eq 0 ]]; then
    exec keepassxc &
fi

if [[ $(pidof Discord | wc -c) -eq 0 ]]; then
    exec Discord --start-minimized &
fi

# if [[ $(pgrep -f element-desktop | wc -c) -eq 0 ]]; then
#     exec element-desktop --hidden &
# fi

if [[ $(pidof syncthing | wc -c) -eq 0 ]]; then
    exec syncthing --no-browser &
fi

if [[ $(pidof copyq | wc -c) -eq 0 ]]; then
    exec copyq &
fi

if [[ $(pgrep solaar | wc -c) -eq 0 ]]; then
    exec solaar -w hide -b regular &
fi

if [[ $(pidof birdtray | wc -c) -eq 0 ]]; then
    exec birdtray &
fi

exec xrdb -merge .Xresources &
exec echo 'exit' | qalc -e &